require('datatables.net/js/jquery.dataTables.js');
require('datatables.net-bs5/js/dataTables.bootstrap5.js');
window.IpixDatatable = require('../../js/components/datatable.js');
window.JSZip = require('jszip/dist/jszip.min.js');
// window.pdfMake = require('pdfmake/build/pdfmake.min.js');
// window.pdfFonts = require('pdfmake/build/vfs_fonts.js');
// window.pdfMake.vfs = window.pdfFonts.pdfMake.vfs;
require('datatables.net-buttons/js/dataTables.buttons.min.js');
require('datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js');
require('datatables.net-buttons/js/buttons.colVis.js');
require('datatables.net-buttons/js/buttons.flash.js');
require('datatables.net-buttons/js/buttons.html5.js');
require('datatables.net-buttons/js/buttons.print.js');
require('datatables.net-colreorder/js/dataTables.colReorder.min.js');
require('datatables.net-colreorder-bs5/js/colReorder.bootstrap5.js');
require('datatables.net-fixedcolumns/js/dataTables.fixedColumns.min.js');
require('datatables.net-fixedcolumns-bs5/js/fixedColumns.bootstrap5.js');
require('datatables.net-fixedheader/js/dataTables.fixedHeader.min.js');
require('datatables.net-fixedheader-bs5/js/fixedHeader.bootstrap5.js');
require('datatables.net-responsive/js/dataTables.responsive.min.js');
require('datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js');
require('datatables.net-rowgroup/js/dataTables.rowGroup.min.js');
require('datatables.net-rowgroup-bs5/js/rowGroup.bootstrap5.js');
require('datatables.net-rowreorder/js/dataTables.rowReorder.min.js');
require('datatables.net-rowreorder-bs5/js/rowReorder.bootstrap5.js');
require('datatables.net-scroller/js/dataTables.scroller.min.js');
require('datatables.net-scroller-bs5/js/scroller.bootstrap5.js');
// require('datatables.net-select/js/dataTables.select.min.js');
// require('datatables.net-select-bs5/js/select.bootstrap5.js');
require('datatables.net-datetime/dist/dataTables.dateTime.min.js');
require('../../js/vendors/plugins/datatables.init.js');